services:
  project-db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: zpi
      POSTGRES_DB: zpi
    volumes:
      - zpi-db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  # redis:
  #   image: redis:8.0-M02-alpine3.20
  #   restart: always
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - zpi-redis-data:/data
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  zpi-db-data:
    driver: local
  # lms-redis-data:
  #   driver: local
